# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /GarbageClassificationAndRecycling

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/garbage_classification_and_recycling?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456


    servlet:
      multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB
    resources:
      static-locations: classpath:static/,file:static/

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
# Physical scanning, multiple packages separated by commas or semicolons  typeAliasesPackage: com.entity
  global-config:
# Primary key type 0:" Database ID increment ", 1:" User input ID",2:" Global unique ID (numeric type unique ID)", 3:" Global unique ID UUID";    id-type: 1
# Field policy 0:" Ignore judgment ",1:" Non-NULL judgment "),2:" Non-null judgment"    field-strategy: 2
    #Hump underscore conversion
    db-column-underline: true
# Refresh mapper Debugger    refresh-mapper: true
    #Logical deletion configuration
    logic-delete-value: -1
    logic-not-delete-value: 0
    #Custom SQL injector
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #The springboot project mybatis plus set jdbcTypeForNull (JdbcType.NULL is required for oracle databases, and the default value is Other).
    jdbc-type-for-null: 'null'

#Print sql statement
logging:
  level:
    com.dao: debug
